config/routes.rb
Rails.application.routes.draw do

root 'broadcasts#index'

get 'login' => 'sessions#new', as: :new_login
delete 'logout' => 'sessions#destroy', as: :logout
post 'login' => 'sessions#create', as: :login

resources :users, only: [:new, :create, :show, :destroy]
resources :broadcasts
resources :reminder_settings, only: [:new, :create, :update, :destroy]

end

app/models/broadcast.rb
class Broadcast < ActiveRecord::Base
  # validates :
  # after_save :notify_by_email

  belongs_to :speaker, class_name: "User"

  has_many :reminder_settings, dependent: :destroy
  has_many :audience_members, through: :reminder_settings, source: :user

  def self.search(search)
    if search
      Broadcast.where('topic iLIKE ?', "%#{search}%")
    else
      Broadcast.all
    end
  end


  def self.upcoming
    Broadcast.where("datetime > ?", DateTime.now)
  end

  def self.an_hour_away
    Broadcast.where("datetime > ?", DateTime.now + 60.minutes).where('datetime < ?', DateTime.now + 120.minutes)
  end

  def self.a_day_away
    Broadcast.where('broadcasts.datetime >= ?', Date.today + 1.day).where('broadcasts.datetime < ?', Date.today + 2.day)
  end

  def readable_time
    self.datetime.strftime("%A, %B %d, %Y at %l%p")
  end

  # def self.belongs_to_current_user?
  #   current_user == self.speaker
  #   binding.pry
  # end
end

app/models/reminder_setting.rb
class ReminderSetting < ActiveRecord::Base

  validates :user, uniqueness: {scope: :broadcast, message: "You have already added that to your saved broadcasts"}

  belongs_to :user
  belongs_to :broadcast

  def unsave
  	self.user.saved_broadcasts.delete(self.broadcast)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :username, :email, presence: true, uniqueness: true

  has_many :broadcasts, foreign_key: "speaker_id"


  has_many :reminder_settings
  has_many :saved_broadcasts, through: :reminder_settings, source: :broadcast

  def self.remindable (broadcast)
    emailable_users = User.get_requesters(broadcast, :email_reminder)
    textable_users = User.get_requesters(broadcast, :text_message)
    [emailable_users, textable_users]
   end

  def self.get_requesters(broadcast, reminder_type)
   broadcast.audience_members.includes(:reminder_settings).where(reminder_settings:{reminder_type => true})
  end

  def user_owns?
    broadcast.speaker == self
  end
  
  def current_user
      @current_user ||= User.find_by(id: session[:user_id])
  end

end

app/models/user_texter.rb
class UserTexter

   TEXT_MESSAGE_BODY = {
      hour_of_reminder: "Greetings from MagicMic! Your broadcast starts in an hour",
      day_before_reminder: "Greetings from MagicMic! You have a saved broadcast tomorrow",
      broadast_updated: "Greetings from MagicMic! A broadcast you saved has been changed",
      broadcast_cancelled: "Greetings from MagicMic! The broadcast you saved,  has been cancelled,"#{broadcast.topic},
  }

  def self.send_message(user, event_type)
      account_sid = ENV["TWILIO_SID"]
      auth_token = ENV["TWILIO_TOKEN"]
      twilio_number = '+13477044254'
      @client = Twilio::REST::Client.new(account_sid, auth_token)
      @client.account.messages.create(
        { :from => twilio_number,
            :to => user.phone_number,
            :body => TEXT_MESSAGE_BODY[event_type]}
      )
    rescue Twilio::REST::RequestError =>error
      puts error.message
    end
  end
#:body => TEXT_MESSAGE_BODY[event_type]}

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # before_action :ensure_current_user, except: [:index, :show]

  helper_method :current_user, :ensure_current_user

  def logged_in?
    !!current_user
  end

  def current_user
    User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def ensure_current_user
    redirect_to login_path unless current_user
  end
end

app/controllers/broadcasts_controller.rb
# require 'twilio_ruby'

class BroadcastsController < ApplicationController
include ApplicationHelper
 before_action :ensure_ownership, only:[:edit,:update,:destroy]

 def index
    @broadcasts = Broadcast.search(params[:search])
  end

  def new
    @broadcast = Broadcast.new
  end

  def create
    if logged_in?
      @broadcast = Broadcast.new(broadcast_params)
      if @broadcast.save
        redirect_to :root
      else
        redirect_to :back
      end
    else
      flash[:error] = "You need to be logged in to create a broadcast"
      redirect_to :back
    end
  end

  def show
    if broadcast_exists?
      @broadcast = Broadcast.find(params[:id])
      @reminder_setting = ReminderSetting.new
    else
      flash[:error]= "No soap, radio."
      redirect_to :root
    end
  end

  def edit
    @broadcast = Broadcast.find(params[:id])
  end

  def update
    @broadcast = Broadcast.find(params[:id])
    @topic = @broadcast.topic
    if @broadcast.update(broadcast_params)
      send_event_notifications
      redirect_to :root
    else
      redirect_to :back
    end
  end

  def destroy
    @broadcast = Broadcast.find(params[:id])
    send_event_notifications(true)
    @broadcast.destroy
    redirect_to :root
  end

  def ensure_ownership
    @broadcast = Broadcast.find(params[:id])
    unless current_user.id == @broadcast.speaker_id
      flash.alert = "Try again"
      redirect_to root_path
    end
  end

  def current_broadcast
    @broadcast = Broadcast.find_by(id:(params[:id]))
  end

  def broadcast_exists?
    current_broadcast != nil
  end

  private

  def send_event_notifications(destroy = false)
    emailable_users, textable_users = User.remindable(@broadcast)
     emailable_users.each do |user|
        if destroy
          UserMailer.broadcast_cancelled(@broadcast, user).deliver_now
        else
          UserMailer.broadcast_updated(@broadcast, user).deliver_now
        end
    end
    textable_users.each do |user|
        UserTexter.send_message(user, :broadcast_cancelled)
    end
  end

  def broadcast_params
    params.require(:broadcast).permit(:topic, :datetime, :duration).merge(speaker_id: current_user.id)
  end
end

app/controllers/calendar_auth_controller.rb
class CalendarAuthController < ApplicationController
	
	def create
		redirect_to: auth_two
	end

	def auth_two
		auth_uri = auth_client.authorization_uri.to_s
	end
end

app/controllers/reminder_settings_controller.rb
class ReminderSettingsController < ApplicationController

  def create
    @reminder_setting = ReminderSetting.new(reminder_params)
    if @reminder_setting.save
      flash[:success] = 'Reminder saved'
      redirect_to :root
    else
      flash[:error] = 'Reminder not saved'
      redirect_to :back
    end
  end

  def destroy
    reminder_setting = ReminderSetting.find_by(user_id: params[:id], broadcast_id: params[:broadcast])
    reminder_setting.unsave
    reminder_setting.destroy
    render text: "Broadcast Un-saved"
  end

  private

  def reminder_params
    params.require(:reminder_setting).permit(:broadcast_id, :email_reminder, :text_message).merge(user: current_user)
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  # skip_before_action :ensure_current_user [:new, :create, :destroy]

   def new
    @user = User.new
  end

  def create
    @user = User.find_by(username: params[:user][:username])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      flash[:success] = "Welcome #{@user.username}"
      redirect_to :root
    else
      flash[:error] = "username or password is incorrect."
      render 'new'
  end
end

  def destroy
    session[:user_id] = nil
    flash[:success] = "GoodBye"
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :ensure_current_user, except: [:new, :create, :show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.welcome_email(@user).deliver_now
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash.alert = "Something went awry. Please try again"
      render 'form'
    end
  end

  def show
    @user = User.find(params[:id])
    redirect_to root_path unless current_user == @user
  end

  def destroy
    user = User.find_by(id: params[:id])
    user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :email)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/broadcasts_helper.rb
module BroadcastsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/broadcasts/_form.html.erb
<%= form_for @broadcast do |f| %>

	<%= f.label :topic %>
  <p>
	<%= f.text_field :topic, autofocus: true%>
  </p>
	<%= f.label :datetime %>
  <div id="date-time">
	<%= f.datetime_select :datetime, order: [:day, :month, :year] %>
  </div>
	<%= f.label :duration %>
  <p>
	<%= f.text_field :duration %>
  </p>
	<%= f.submit :submit %>


<% end %>

app/views/broadcasts/_mic.html.erb
<div id="mic">
  <%= link_to image_tag("mic.png"), "https://magic-mic-socket-server.herokuapp.com" + "?room=room#{@broadcast.id}"  %>
</div>

app/views/broadcasts/_play.html.erb
<div id="play">
  <%= link_to image_tag("play.png"), "https://magic-mic-socket-server.herokuapp.com" + "?room=room#{@broadcast.id}"  %>
</div>

app/views/broadcasts/edit.html.erb
<div class="page-and-form">
<h2>Update Broadcast Details</h2>

<%= render 'form' %>

</div>

app/views/broadcasts/index.html.erb
<div class="page-and-form">
<h2>Upcoming Broadcasts</h2>
<%= form_tag broadcasts_path, method: 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>


<% if @broadcasts %>
  <% @broadcasts.each do |stream| %>
    <p><%= link_to stream.topic, broadcast_path(stream) %></p>
  <% end %>
<% end %>






</div>

app/views/broadcasts/new.html.erb
<div class="page-and-form">
<h2>Schedule a Broadcast</h2>

<%= render 'form' %>

</div>

app/views/broadcasts/show.html.erb
<div class="broadcast-show-page">
  <h1 id="broadcast-show-header" ><%= @broadcast.topic %></h1>
  <h3 id="broadcast-time-header"><%= @broadcast.readable_time %></h3>

<p>
<% if @broadcast.speaker == current_user %>
  <%= link_to "Change Broadcast Details", edit_broadcast_path(@broadcast) %> |
  <%= link_to "Cancel This Broadcast", broadcast_path(@broadcast), method: :delete %>
    <p>
    <%= image_tag("mic.png")%>
    </p>
<% else %>
  <p>
     <%= render 'reminder_settings/form', locals: {reminder_setting: @reminder_setting}  %>
    <div id="reminder_signup">
      <p>
    <% if ReminderSetting.find_by(user_id: current_user.id, broadcast_id: @broadcast.id) %>
    
      <button id="unsave-button">Unsave</button>
    <% else %>
      <button id="save-button">Save</button>
      </p>
    </div>
        <%= image_tag("listen.png")%>
      </p>
    <% end %>
    <% end %>
</p>

<div id="audio-container"></div>
  <button id="open-or-join" data-room="room<%=@broadcast.id%>"> </button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MagicMic</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <script src="https://magic-mic-socket-server.herokuapp.com/socket.io/socket.io.js"></script>
  <script src="https://magic-mic-socket-server.herokuapp.com/RTCMultiConnection.js"></script>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Noto+Sans' rel='stylesheet' type='text/css'>
</head>
<body>

<header>
  <nav>
  <div id="app-name-head">MagicMic</div>
   <ul id="nav">
    <% if current_user %>
      <li><%= link_to "Logout", logout_path, method: :delete %></li> |
      <li><%= link_to "My Upcoming Broadcasts", user_path(current_user) %></li> |
    <% else %>
      <li><%= link_to "Login", new_login_path %></li> |
      <li><%= link_to "Signup", new_user_path %></li> |
    <% end %>
    <li><a href="/">Broadcasts</a></li> |
    <li><%= link_to 'Schedule a Broadcast', new_broadcast_path %></li>
  </ul>
  </nav>
</header>

 <div id="greeting">
 <% if flash.any? %>
   <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
    <% end %>
  <% end %>
  </div>


<%= yield %>

</body>
</html>

app/views/reminder_settings/_form.html.erb
<div id="reminder-settings-form">
  <%= form_for @reminder_setting do |f| %>
  <p>Would you like us to send you email or sms reminders?</p>
    <%= f.hidden_field :broadcast_id, value: @broadcast.id %>

    <%= f.check_box(:email_reminder) %>
    <%= f.label :email%>
    <%= f.check_box(:text_message) %>
    <%= f.label :text%>

    <%= f.submit :submit %>

  <% end %>
</div>

app/views/reminder_settings/new.html.erb
<%= render 'form' %>

app/views/users/_broadcast_link.html.erb
<div id="unsave-container-<%= broadcast.id%>">
  <p>
    <%= link_to broadcast.topic, broadcast_path(broadcast), class: "saved-broadcast-link" %>   <%= link_to "(x)", reminder_setting_path(@user,{broadcast: broadcast}), class: "unsave-link" %>
  </p>
</div>

app/views/users/_form.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <%= f.label :username %>
  <br>
  <%= f.text_field :username, autofocus: true %>
  <br>
  <%= f.label :password %>
  <br>
  <%= f.password_field :password %>
  <br>
  <%= f.label :email %>
  <br>
  <%= f.text_field :email %>
  <br>
  <%= f.submit "Submit" %>

<% end %>

app/views/users/new.html.erb
<div class="page-and-form">

<%= render 'form' %>

</div>

app/views/users/show.html.erb
<div class="page-and-form">

  <h3>Your Scheduled Broadcasts</h3>

  <% if @user.broadcasts%>
    <% @user.broadcasts.each do |broadcast| %>
      <p><%= link_to broadcast.topic, broadcast_path(broadcast) %></p>
    <% end %>
  <% end %>

  <h3> Your Saved Broadcasts </h3>

  <% if @user.saved_broadcasts %>
    <% @user.saved_broadcasts.each do |broadcast| %>
     <%= render partial: "broadcast_link", layout: false, locals: {broadcast: broadcast} %>
    <% end %>
  <% end %>


</div>